spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
    #table-prefix: batch
  application:
    name: pyz_demo
  redis:
    host: 127.0.0.1
    port: 6371
    timeout: 20000
    cluster:
      nodes: 127.0.0.1:6372,127.0.0.1:6373
      maxRedirects: 6
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    #邮箱配置
  mail:
    host: smtp.163.com
    from: xhhuiblog@163.com
      # 使用自己的发送方用户名 + 授权码填充
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
