spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
    #table-prefix: batch
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/db_base?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
